# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emission.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 10, 231, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 70, 104, 21))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 120, 104, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(30, 180, 111, 22))
        self.spinBox.setObjectName("spinBox")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 230, 91, 32))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.origin = QtWidgets.QLabel(Dialog)
        self.origin.setGeometry(QtCore.QRect(30, 50, 58, 16))
        self.origin.setObjectName("origin")
        self.destination = QtWidgets.QLabel(Dialog)
        self.destination.setGeometry(QtCore.QRect(30, 100, 101, 16))
        self.destination.setObjectName("destination")
        self.cargoMass = QtWidgets.QLabel(Dialog)
        self.cargoMass.setGeometry(QtCore.QRect(30, 160, 101, 16))
        self.cargoMass.setObjectName("cargoMass")
        self.modeTrans = QtWidgets.QLabel(Dialog)
        self.modeTrans.setGeometry(QtCore.QRect(30, 220, 121, 16))
        self.modeTrans.setObjectName("modeTrans")
        self.emission = QtWidgets.QLabel(Dialog)
        self.emission.setGeometry(QtCore.QRect(170, 50, 111, 16))
        self.emission.setObjectName("emission")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(170, 70, 101, 21))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Greenhouse Gas Emission Calculator"))
        self.comboBox.setItemText(0, _translate("Dialog", "air"))
        self.comboBox.setItemText(1, _translate("Dialog", "rail"))
        self.comboBox.setItemText(2, _translate("Dialog", "road"))
        self.origin.setText(_translate("Dialog", "Origin"))
        self.destination.setText(_translate("Dialog", "Destination"))
        self.cargoMass.setText(_translate("Dialog", "Cargo Mass (kg)"))
        self.modeTrans.setText(_translate("Dialog", "Mode of Transport"))
        self.emission.setText(_translate("Dialog", "CO2 Emissions (g)"))
