# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emission.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 10, 231, 16))
        self.label.setObjectName("label")
        self.textEdit_origin = QtWidgets.QTextEdit(Dialog)
        self.textEdit_origin.setGeometry(QtCore.QRect(30, 70, 104, 21))
        self.textEdit_origin.setObjectName("textEdit_origin")
        self.textEdit_dest = QtWidgets.QTextEdit(Dialog)
        self.textEdit_dest.setGeometry(QtCore.QRect(30, 120, 104, 21))
        self.textEdit_dest.setObjectName("textEdit_dest")
        self.comboBox_mode = QtWidgets.QComboBox(Dialog)
        self.comboBox_mode.setGeometry(QtCore.QRect(30, 230, 91, 32))
        self.comboBox_mode.setObjectName("comboBox_mode")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.origin = QtWidgets.QLabel(Dialog)
        self.origin.setGeometry(QtCore.QRect(30, 50, 58, 16))
        self.origin.setObjectName("origin")
        self.destination = QtWidgets.QLabel(Dialog)
        self.destination.setGeometry(QtCore.QRect(30, 100, 101, 16))
        self.destination.setObjectName("destination")
        self.mass = QtWidgets.QLabel(Dialog)
        self.mass.setGeometry(QtCore.QRect(30, 160, 101, 16))
        self.mass.setObjectName("mass")
        self.modeTrans = QtWidgets.QLabel(Dialog)
        self.modeTrans.setGeometry(QtCore.QRect(30, 220, 121, 16))
        self.modeTrans.setObjectName("modeTrans")
        self.emission = QtWidgets.QLabel(Dialog)
        self.emission.setGeometry(QtCore.QRect(170, 50, 111, 16))
        self.emission.setObjectName("emission")
        self.textBrowser_emission = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_emission.setGeometry(QtCore.QRect(170, 70, 101, 21))
        self.textBrowser_emission.setObjectName("textBrowser_emission")
        self.textEdit_mass = QtWidgets.QTextEdit(Dialog)
        self.textEdit_mass.setGeometry(QtCore.QRect(30, 180, 104, 21))
        self.textEdit_mass.setObjectName("textEdit_mass")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Greenhouse Gas Emission Calculator"))
        self.comboBox_mode.setItemText(0, _translate("Dialog", "air"))
        self.comboBox_mode.setItemText(1, _translate("Dialog", "rail"))
        self.comboBox_mode.setItemText(2, _translate("Dialog", "road"))
        self.origin.setText(_translate("Dialog", "Origin"))
        self.destination.setText(_translate("Dialog", "Destination"))
        self.mass.setText(_translate("Dialog", "Cargo Mass (kg)"))
        self.modeTrans.setText(_translate("Dialog", "Mode of Transport"))
        self.emission.setText(_translate("Dialog", "CO2 Emissions (g)"))
