# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emission2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(495, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mass = QtWidgets.QLabel(self.centralwidget)
        self.mass.setGeometry(QtCore.QRect(30, 160, 101, 16))
        self.mass.setObjectName("mass")
        self.comboBox_mode = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_mode.setGeometry(QtCore.QRect(30, 230, 91, 32))
        self.comboBox_mode.setObjectName("comboBox_mode")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 231, 16))
        self.label.setObjectName("label")
        self.origin = QtWidgets.QLabel(self.centralwidget)
        self.origin.setGeometry(QtCore.QRect(30, 50, 58, 16))
        self.origin.setObjectName("origin")
        self.textEdit_mass = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_mass.setGeometry(QtCore.QRect(30, 180, 104, 21))
        self.textEdit_mass.setObjectName("textEdit_mass")
        self.textBrowser_emission = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_emission.setGeometry(QtCore.QRect(170, 70, 101, 21))
        self.textBrowser_emission.setObjectName("textBrowser_emission")
        self.modeTrans = QtWidgets.QLabel(self.centralwidget)
        self.modeTrans.setGeometry(QtCore.QRect(30, 220, 121, 16))
        self.modeTrans.setObjectName("modeTrans")
        self.textEdit_origin = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_origin.setGeometry(QtCore.QRect(30, 70, 104, 21))
        self.textEdit_origin.setObjectName("textEdit_origin")
        self.textEdit_dest = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_dest.setGeometry(QtCore.QRect(30, 120, 104, 21))
        self.textEdit_dest.setObjectName("textEdit_dest")
        self.emission = QtWidgets.QLabel(self.centralwidget)
        self.emission.setGeometry(QtCore.QRect(170, 50, 111, 16))
        self.emission.setObjectName("emission")
        self.destination = QtWidgets.QLabel(self.centralwidget)
        self.destination.setGeometry(QtCore.QRect(30, 100, 101, 16))
        self.destination.setObjectName("destination")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 60, 112, 32))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 495, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mass.setText(_translate("MainWindow", "Cargo Mass (kg)"))
        self.comboBox_mode.setItemText(0, _translate("MainWindow", "air"))
        self.comboBox_mode.setItemText(1, _translate("MainWindow", "rail"))
        self.comboBox_mode.setItemText(2, _translate("MainWindow", "road"))
        self.label.setText(_translate("MainWindow", "Greenhouse Gas Emission Calculator"))
        self.origin.setText(_translate("MainWindow", "Origin"))
        self.modeTrans.setText(_translate("MainWindow", "Mode of Transport"))
        self.emission.setText(_translate("MainWindow", "CO2 Emissions (g)"))
        self.destination.setText(_translate("MainWindow", "Destination"))
        self.pushButton.setText(_translate("MainWindow", "calculate"))
