import sys

from get_distance import calculate_distance
from get_emissions import calculate_emissions

url = "https://distanceto.p.rapidapi.com/get"

# script can be run from the command line using 'python3 main.py <origin> <destination> <mode> <mass>'
origin = sys.argv[1]
destination = sys.argv[2]
mode = sys.argv[3]
# I made mass an optional argument-- if it isn't supplied, it will default to 1kg (the output will
# represent the emissions generated by moving 1kg from origin to destination)
if len(sys.argv) == 5:
    mass = sys.argv[4]
else:
    mass = 1

if __name__ == '__main__':
    # call on helper functions to compute distance between origin and destination and to calculate
    # C02 emissions based on mode of transport
    dist = calculate_distance(origin, destination)
    emissions = calculate_emissions(dist, mode, mass)
    print(str(emissions) + 'g of carbon emissions created')

    # if we want to present multiple emissions-types to user at once
    # air_emissions = calculate_emissions(dist, 'air', mass)
    # ground_emissions = calculate_emissions(dist, 'ground', mass)
    # rail_emissions = calculate_emissions(dist, 'rail', mass)
